"""Generate scaled copies of the tutorial world for performance testing.

Lives in ``tools/`` rather than ``tests/`` because both the in-process
benchmarks and the disposable browser-test runtime need it, and ``tools/`` is
the lower layer of the two.

Everything is generated by cloning the checked-in tutorial content, so the
content loaders, propsets, mods and effect catalog are identical to what ships.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from typing import Any

import yaml


#: A prop that exists in the tutorial propsets and carries effects, so generated
#: rooms exercise the same serialisation work as authored content.
BULK_PROP_ID = "plant"
BULK_PEEP_IMAGE = "molly.png"
ENTRY_ROOM = "hub"
WORLD_ID = "tutorial"


def _link_or_copy(source: str, destination: str) -> None:
    try:
        os.link(source, destination)
    except OSError:
        shutil.copy2(source, destination)


def _write_yaml(path: Path, payload: Any) -> None:
    """Overwrite *path*, breaking any hardlink to the original first.

    The world tree is hardlinked to avoid copying megabytes of artwork, so a
    plain ``write_text`` would truncate the shared inode and silently corrupt
    the checked-in world definition. Unlinking first guarantees a fresh inode.
    """

    if path.exists() or path.is_symlink():
        path.unlink()
    path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")


def build_scaled_world(
    destination: Path,
    *,
    rooms: int = 0,
    props_per_room: int = 0,
    peeps_per_room: int = 0,
    cards_per_room: int = 0,
    aura_rooms: int = 0,
    room_prefix: str = "perf",
    peep_prefix: str = "perfpeep",
    cards: tuple[str, ...] | None = None,
) -> Path:
    """Write a copy of the tutorial world scaled up along the requested axes.

    ``rooms`` clones the entry room, so palette, board image and exits all stay
    valid. ``props_per_room``/``peeps_per_room``/``cards_per_room`` inflate the
    entry room, because that is the one the benchmarks occupy. ``aura_rooms``
    gives the first N rooms a stat aura, since the checked-in tutorial world
    defines none and the ticker behaves differently without one.
    """

    repo_root = Path(__file__).resolve().parents[1]
    tutorial_path = repo_root / "worlds" / WORLD_ID
    target = destination / WORLD_ID
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(tutorial_path, target, copy_function=_link_or_copy)

    rooms_payload = yaml.safe_load((target / "rooms" / "rooms.yaml").read_text(encoding="utf-8"))
    peeps_payload = yaml.safe_load((target / "peeps" / "peeps.yaml").read_text(encoding="utf-8"))
    template = rooms_payload[ENTRY_ROOM]

    entry_props = dict(template.get("props") or {})
    for index in range(props_per_room):
        entry_props[f"bulk-prop-{index}"] = {
            "prop": BULK_PROP_ID,
            "pos": [5 + (index % 20) * 4.5, 8 + (index // 20) * 4.5, 0],
            "rot": [0, 0, 0],
            "scale": 0.6,
        }
    if entry_props:
        template["props"] = entry_props

    if cards_per_room:
        pool = cards if cards is not None else card_pool()
        entry_cards = list(template.get("cards") or [])
        for index in range(cards_per_room):
            entry_cards.append(
                {
                    "card": pool[index % len(pool)],
                    "quantity": 1,
                    "pos": [6 + (index % 10) * 8, 12 + (index // 10) * 8, 0],
                }
            )
        template["cards"] = entry_cards

    if aura_rooms:
        # A stat aura plus a timed buff, so both the modifier and the buff
        # branches of AuraService.enter are exercised.
        template["aura"] = [
            {"stat": "max_health", "delta": 2.0, "duration": 3600},
            {"buff": "s1", "duration": 3600},
        ]

    for index in range(rooms):
        clone = yaml.safe_load(yaml.safe_dump(template))
        clone["label"] = f"Synthetic Room {index}"
        clone["description"] = "Generated room used by the performance suite."
        clone["exits"] = {"back": {"label": "Back", "target": ENTRY_ROOM}}
        if index >= aura_rooms:
            clone.pop("aura", None)
        rooms_payload[f"{room_prefix}-{index}"] = clone

    for index in range(peeps_per_room):
        peeps_payload[f"{peep_prefix}-{index}"] = {
            "label": f"Perf Peep {index}",
            "description": "Generated NPC used by the performance suite.",
            "room": ENTRY_ROOM,
            "image": BULK_PEEP_IMAGE,
            "actions": [["Greet", ".look"]],
        }

    _write_yaml(target / "rooms" / "rooms.yaml", rooms_payload)
    _write_yaml(target / "peeps" / "peeps.yaml", peeps_payload)
    return target


def card_pool(limit: int = 8) -> tuple[str, ...]:
    """Return a stable tuple of card ids usable as room-card content."""

    from server.content.cards import load_card_catalog

    repo_root = Path(__file__).resolve().parents[1]
    catalog = load_card_catalog(repo_root / "data" / "cardsets", repo_root / "worlds" / WORLD_ID)
    return tuple(sorted(catalog.cards)[:limit])


def parse_scale(value: str) -> dict[str, int]:
    """Parse a ``--world-scale`` value such as ``"props=90,peeps=12"``."""

    scale: dict[str, int] = {}
    for part in value.split(","):
        part = part.strip()
        if not part:
            continue
        key, _, raw = part.partition("=")
        if key not in {
            "rooms",
            "props_per_room",
            "peeps_per_room",
            "cards_per_room",
            "aura_rooms",
        }:
            raise ValueError(f"Unknown world-scale key '{key}'.")
        scale[key] = int(raw or 0)
    return scale
